import os
import sys
import rtconfig

from rtconfig import RTT_ROOT

sys.path = sys.path + [os.path.join(RTT_ROOT, 'tools')]
from building import *

TARGET = 'rtthread.' + rtconfig.TARGET_EXT

DefaultEnvironment(tools=[])
env = Environment(tools = ['mingw'],
    AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
    CC = rtconfig.CC, CCFLAGS = rtconfig.CFLAGS,
    CXX = rtconfig.CXX, CXXFLAGS = rtconfig.CXXFLAGS,
    AR = rtconfig.AR, ARFLAGS = '-rc',
    LINK = rtconfig.LINK, LINKFLAGS = rtconfig.LFLAGS)
env.PrependENVPath('PATH', rtconfig.EXEC_PATH)
env['ASCOM'] = env['ASPPCOM']

Export('RTT_ROOT')
Export('rtconfig')

_am_arch = os.environ.get('ARCH', '')
if _am_arch.startswith('riscv32e'):
    rtconfig.CPU = 'rv32e'
    rtconfig.ARCH = 'risc-v'
elif _am_arch.startswith('riscv32'):
    rtconfig.CPU = 'rv32'
    rtconfig.ARCH = 'risc-v'
elif _am_arch.startswith('riscv64'):
    rtconfig.CPU = 'virt64'
    rtconfig.ARCH = 'risc-v'
else:
    rtconfig.CPU = 'virt64'
    rtconfig.ARCH = 'risc-v'

# prepare building environment
objs = PrepareBuilding(env, RTT_ROOT, has_libcpu = True)

# make a building
DoBuilding(TARGET, objs)
